# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
switch = "r"
mode = "station"
esc_quit = true

# =============================================================================== #
# Device:                                                                         #
# =============================================================================== #
[device]
infos = "i"
toggle_power = "o"

# =============================================================================== #
# Access:                                                                         #
# =============================================================================== #
[access_point]
start = 'n'
stop = 'x'

# =============================================================================== #
# Station:                                                                        #
# =============================================================================== #
[station]
toggle_scanning = "s"

[station.known_network]
toggle_autoconnect = "t"
remove = "d"
show_all = "a"
share = "p"

# [station.new_network]
# show_all = "a"
# connect_hidden = ""
