-- ============================================================================== #
-- Keymaps:                                                                       #
-- ============================================================================== #
Config.later(function()
  -- Disable: ====================================================================================
  vim.keymap.set('n', 'Q', '<nop>')
  vim.keymap.set('n', '<Space>', '<Nop>')
  vim.keymap.set('i', '<C-H>', '<Nop>')
  vim.keymap.set('i', '<C-L>', '<Nop>')
  vim.keymap.set('i', '<C-J>', '<Nop>')
  vim.keymap.set('i', '<C-K>', '<Nop>')

  -- Rsi mappings: ===============================================================================
  vim.keymap.set('c', '<C-a>', '<Home>')
  vim.keymap.set('c', '<C-e>', '<End>')
  vim.keymap.set('c', '<C-j>', '<down>')
  vim.keymap.set('c', '<C-k>', '<up>')

  -- General: ====================================================================================
  vim.keymap.set('n', '<leader>qq', '<cmd>qa<cr>')
  vim.keymap.set('n', '<leader>rc', '<cmd>EditConfig<cr>')
  vim.keymap.set('n', '<Leader>re', '<cmd>write | restart<cr>')
  vim.keymap.set('n', '<leader>y', '<cmd>%yank<cr>')
  vim.keymap.set('n', '<leader>p', 'm`o<ESC>p``')
  vim.keymap.set('n', '<leader>P', 'm`O<ESC>p``')
  vim.keymap.set('n', '<leader>M', '<cmd>messages<cr>')
  vim.keymap.set('n', '<leader>uu', ':earlier ')
  vim.keymap.set('n', '<leader><leader>', 'zz')
  vim.keymap.set('n', '<ESC>', '<cmd>silent nohl<cr>')
  vim.keymap.set('n', '<C-s>', '<cmd>silent update<cr>')
  vim.keymap.set('i', '<C-s>', '<Esc><cmd>silent update<cr>')
  vim.keymap.set('i', '<C-b>', '<Esc><right>dwgi')
  vim.keymap.set('i', '<c-t>', '<Esc>b~lea')
  vim.keymap.set('i', '<C-A>', '<HOME>')
  vim.keymap.set('i', '<C-E>', '<END>')
  vim.keymap.set('i', '<c-y>', '<Esc>viwUea')
  vim.keymap.set('n', '<c-y>', '<c-y><c-y><c-y>')
  vim.keymap.set('n', '<c-e>', '<c-e><c-e><c-e>')
  vim.keymap.set('n', '<C-i>', 'gg=G``')
  vim.keymap.set('n', '<C-m>', '%')
  vim.keymap.set('v', '<TAB>', '>gv')
  vim.keymap.set('v', '<S-TAB>', '<gv')
  vim.keymap.set('x', '<TAB>', '>gv')
  vim.keymap.set('x', '<S-TAB>', '<gv')
  vim.keymap.set('v', '<', '<gv')
  vim.keymap.set('v', '>', '>gv')
  vim.keymap.set('x', 'gr', '"_dP')
  vim.keymap.set('n', 'gk', 'gg')
  vim.keymap.set('n', 'gj', 'G')
  vim.keymap.set('n', 'gh', '^')
  vim.keymap.set('n', 'gl', 'g_')
  vim.keymap.set('v', 'gk', 'gg')
  vim.keymap.set('v', 'gj', 'G')
  vim.keymap.set('v', 'gh', '^')
  vim.keymap.set('v', 'gl', '$')
  vim.keymap.set('n', 'gy', '`[v`]')
  vim.keymap.set('n', 'g/', '*')
  vim.keymap.set('n', 'g*', 'g*N')
  vim.keymap.set('n', 'g#', 'g#N')
  vim.keymap.set('x', '/', '<Esc>/\\%V')
  vim.keymap.set('n', '!', 'v~')
  vim.keymap.set('n', ';', ':')
  vim.keymap.set('x', ';', ':')
  vim.keymap.set('n', 'U', '<C-r>')
  vim.keymap.set('x', 'R', ':s###g<left><left><left>')
  vim.keymap.set('n', 'J', 'mzJ`z:delmarks z<cr>')
  vim.keymap.set('n', 'yG', 'yG`]')
  vim.keymap.set('v', 'y', 'y`]')
  vim.keymap.set('v', 'p', 'p`]')
  vim.keymap.set('n', 'p', 'p`]')
  vim.keymap.set('n', 'x', '"_x')
  vim.keymap.set('n', 'X', '"_0D')
  vim.keymap.set('n', 'c', '"_c')
  vim.keymap.set('n', 'cc', '"_cc')
  vim.keymap.set('n', 'C', '"_C')
  vim.keymap.set('x', 'c', '"_c')
  vim.keymap.set('x', '$', 'g_')
  vim.keymap.set('v', 'J', ":m '>+1<cr>gv=gv")
  vim.keymap.set('v', 'K', ":m '<-2<cr>gv=gv")
  vim.keymap.set('x', 'J', ":move '>+1<CR>gv-gv")
  vim.keymap.set('x', 'K', ":move '<-2<CR>gv-gv")
  vim.keymap.set('c', '%%', "<C-R>=expand('%:h').'/'<cr>")
  vim.keymap.set('n', '}', '<cmd>execute "keepjumps norm! " . v:count1 . "}"<cr>')
  vim.keymap.set('n', '{', '<cmd>execute "keepjumps norm! " . v:count1 . "{"<cr>')
  vim.keymap.set('n', 'yco', 'o<esc>Vcx<esc><cmd>normal gcc<cr>fxa<bs>')
  vim.keymap.set('n', 'ycO', 'O<esc>Vcx<esc><cmd>normal gcc<cr>fxa<bs>')
  vim.keymap.set('n', 'ycc', 'yygccp', { remap = true })
  vim.keymap.set('n', 'gV', '"`[" . strpart(getregtype(), 0, 1) . "`]"', { expr = true })
  vim.keymap.set('n', 'u', ':silent undo<cr>', { silent = true })
  vim.keymap.set('n', 'U', ':silent redo<cr>', { silent = true })
  vim.keymap.set('n', '<C-r>', ':silent redo<cr>', { silent = true })
  vim.keymap.set('n', '<C-c>', 'cit', { remap = true })
  vim.keymap.set('i', '<C-c>', '<Esc>cit', { remap = true })
  vim.keymap.set('n', '<C-q>', 'ciq', { remap = true })
  vim.keymap.set('i', '<C-q>', '<Esc>ciq', { remap = true })
  vim.keymap.set('n', '<C-w>', 'ciw', { remap = true })
  vim.keymap.set('i', '<C-w>', '<Esc>ciw', { remap = true })
  vim.keymap.set('n', '<C-n>', '*N', { remap = true })
  vim.keymap.set('n', '<C-N>', '*n', { remap = true })
  vim.keymap.set('n', '<leader>o', "printf('m`%so<ESC>``', v:count1)", { expr = true })
  vim.keymap.set('n', '<leader>O', "printf('m`%sO<ESC>``', v:count1)", { expr = true })
  vim.keymap.set('n', '<leader>v', "printf('`[%s`]', getregtype()[0])", { expr = true })

  -- Completion: =================================================================================
  vim.keymap.set('i', '<C-j>', [[pumvisible() ? "\<C-n>" : "\<C-j>"]], { expr = true })
  vim.keymap.set('i', '<C-k>', [[pumvisible() ? "\<C-p>" : "\<C-k>"]], { expr = true })

  -- Jumplist ====================================================================================
  vim.keymap.set('n', '<C-i>', '<C-i>zz', { silent = true })
  vim.keymap.set('n', '<C-o>', '<C-o>zz', { silent = true })

  -- Diagnostic:==================================================================================
  vim.keymap.set('n', 'dg', '<cmd>ToggleDiagnosticStyle<cr>')
  vim.keymap.set('n', 'dq', '<cmd>lua vim.diagnostic.setqflist()<cr>')
  vim.keymap.set('n', 'dl', '<cmd>lua vim.diagnostic.setloclist()<cr>')
  vim.keymap.set('n', 'do', '<cmd>lua vim.diagnostic.open_float()<cr>')

  -- Subtitle: ==================================================================================
  vim.keymap.set('n', '<Leader>rs', [[:%s/\<<C-r><C-w>\>//g<Left><Left>]])
  vim.keymap.set('n', '<leader>rr', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])

  -- Surround: ==================================================================================
  vim.keymap.set('n', 'sq', '<cmd>SurroundOrReplaceQuotes<cr>')
  vim.keymap.set('x', 'S', [[:<C-u>lua MiniSurround.add('visual')<CR>]])

  -- Focus : =====================================================================================
  vim.keymap.set('n', '<C-H>', '<C-w>h')
  vim.keymap.set('n', '<C-J>', '<C-w>j')
  vim.keymap.set('n', '<C-K>', '<C-w>k')
  vim.keymap.set('n', '<C-L>', '<C-w>l')

  -- Move: =======================================================================================
  vim.keymap.set('n', '<leader>L', '<C-w>L')
  vim.keymap.set('n', '<leader>H', '<C-w>H')
  vim.keymap.set('n', '<leader>K', '<C-w>K')
  vim.keymap.set('n', '<leader>J', '<C-w>J')

  -- Resize: =====================================================================================
  vim.keymap.set('n', '<C-Up>', '<cmd>resize +2<cr>')
  vim.keymap.set('n', '<C-Down>', '<cmd>resize -2<cr>')
  vim.keymap.set('n', '<C-Left>', '<cmd>vertical resize -2<cr>')
  vim.keymap.set('n', '<C-Right>', '<cmd>vertical resize +2<cr>')

  -- Center:  ====================================================================================
  vim.keymap.set('n', 'n', 'nzzzv')
  vim.keymap.set('n', 'N', 'Nzzzv')
  vim.keymap.set('n', '<C-d>', '<C-d>zz')
  vim.keymap.set('n', '<C-u>', '<C-u>zz')

  -- Theme: ======================================================================================
  vim.keymap.set('n', '<leader>tt', '<cmd>ToggleBgMode<cr>')
  vim.keymap.set('n', '<leader>td', '<cmd>set background=dark<cr>')
  vim.keymap.set('n', '<leader>tl', '<cmd>set background=light<cr>')
  vim.keymap.set('n', '<leader>tr', '<cmd>colorscheme randomhue<cr>')

  -- Terminal: ===================================================================================
  vim.keymap.set('t', '<Esc><Esc>', [[<C-\><C-n>]])
  vim.keymap.set('t', '<C-h>', [[<Cmd>wincmd h<CR>]])
  vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]])
  vim.keymap.set('t', '<C-k>', [[<Cmd>wincmd k<CR>]])
  vim.keymap.set('t', '<C-l>', [[<Cmd>wincmd l<CR>]])
  vim.keymap.set('t', '<C-w>', [[<C-\><C-n><C-w>]])
  vim.keymap.set('t', '<C-t>', [[<Cmd>TermToggle<CR>]])
  vim.keymap.set('n', '<C-t>', [[<Cmd>TermToggle<CR>]])

  -- Buffers: ====================================================================================
  vim.keymap.set('n', '<Tab>', '<cmd>bnext<cr>')
  vim.keymap.set('n', '<S-Tab>', '<cmd>bprevious<cr>')
  vim.keymap.set('n', '<leader><tab>', '<cmd>b#<cr>')
  vim.keymap.set('n', '<leader>ba', '<cmd>b#<cr>')
  vim.keymap.set('n', '<leader>bn', '<cmd>bnext<cr>')
  vim.keymap.set('n', '<leader>bp', '<cmd>bprevious<cr>')
  vim.keymap.set('n', '<leader>bm', '<cmd>ZoomBuffer<cr>')
  vim.keymap.set('n', '<leader>bd', '<cmd>DeleteBuffer<cr>')
  vim.keymap.set('n', '<leader>bb', '<cmd>DeleteOtherBuffers<cr>')
  vim.keymap.set('n', '<leader>bi', '<cmd>DeleteInactiveBuffers<cr>')
  vim.keymap.set('n', '<leader>bf', '<cmd>Format<cr>')

  -- Quickfix: ===================================================================================
  vim.keymap.set('n', '<leader>cc', '<cmd>ExploreQuickfix<CR>')
  vim.keymap.set('n', '<leader>ct', '<cmd>ExploreQuickfix<CR>')
  vim.keymap.set('n', '<leader>co', '<cmd>copen<CR>')
  vim.keymap.set('n', '<leader>cq', '<cmd>cclose<CR>')
  vim.keymap.set('n', '<leader>cn', '<cmd>cnext<CR>')
  vim.keymap.set('n', '<leader>cp', '<cmd>cprev<CR>')

  -- Location: ===================================================================================
  vim.keymap.set('n', '<leader>lt', '<cmd>ExploreLocations<CR>')
  vim.keymap.set('n', '<leader>lo', '<cmd>lopen<CR>')
  vim.keymap.set('n', '<leader>lq', '<cmd>lclose<CR>')
  vim.keymap.set('n', '<leader>ln', '<cmd>lnext<CR>')
  vim.keymap.set('n', '<leader>lp', '<cmd>lprev<CR>')

  -- Spell: ======================================================================================
  vim.keymap.set('n', '<leader>st', '<cmd>set spell!<cr>')
  vim.keymap.set('n', '<leader>sr', '<cmd>spellr<cr>')
  vim.keymap.set('n', '<leader>sn', ']s')
  vim.keymap.set('n', '<leader>sp', '[s')
  vim.keymap.set('n', '<leader>ss', 'z=')
  vim.keymap.set('n', '<leader>sa', 'zg')
  vim.keymap.set('n', '<leader>sd', 'zw')
  vim.keymap.set('n', '<leader>s?', 'z?')

  -- Directories: ================================================================================
  vim.keymap.set('n', '<leader>e', '<cmd>Explorer<cr>')
  vim.keymap.set('n', '<leader>cd', '<cmd>Cwd<cr>')
  vim.keymap.set('n', '<leader>cr', '<cmd>Crd<cr>')

  -- window: =====================================================================================
  vim.keymap.set('n', '<leader>qw', '<cmd>close<cr>')
  vim.keymap.set('n', '<leader>wq', '<cmd>close<cr>')
  vim.keymap.set('n', '<leader>wc', '<cmd>close<cr>')
  vim.keymap.set('n', '<leader>wo', '<cmd>only<cr>')
  vim.keymap.set('n', '<leader>wv', '<cmd>split<cr>')
  vim.keymap.set('n', '<leader>ws', '<cmd>vsplit<cr>')
  vim.keymap.set('n', '<leader>wb', '<cmd>vsplit<cr>')
  vim.keymap.set('n', '<leader>|', '<cmd>wincmd v<cr>')
  vim.keymap.set('n', '<leader>-', '<cmd>wincmd s<cr>')
  vim.keymap.set('n', '<leader>wT', '<cmd>wincmd T<cr>')
  vim.keymap.set('n', '<leader>wr', '<cmd>wincmd r<cr>')
  vim.keymap.set('n', '<leader>wR', '<cmd>wincmd R<cr>')
  vim.keymap.set('n', '<leader>wH', '<cmd>wincmd H<cr>')
  vim.keymap.set('n', '<leader>wJ', '<cmd>wincmd J<cr>')
  vim.keymap.set('n', '<leader>wK', '<cmd>wincmd K<cr>')
  vim.keymap.set('n', '<leader>wL', '<cmd>wincmd L<cr>')
  vim.keymap.set('n', '<leader>w=', '<cmd>wincmd =<cr>')
  vim.keymap.set('n', '<leader>w0', '<cmd>wincmd =<cr>')
  vim.keymap.set('n', '<leader>wk', '<cmd>resize +10<cr>')
  vim.keymap.set('n', '<leader>wj', '<cmd>resize -10<cr>')
  vim.keymap.set('n', '<leader>wh', '<cmd>vertical resize +10<cr>')
  vim.keymap.set('n', '<leader>wl', '<cmd>vertical resize -10<cr>')
  vim.keymap.set('n', '<leader>ww', '<cmd>RotateWindows<cr>')
  vim.keymap.set('n', '<leader>wm', '<cmd>MoveWindowToTab<cr>')

  -- Misc: =======================================================================================
  vim.keymap.set('n', 's', '<cmd>EasyMotion<cr>')
  vim.keymap.set('n', 'gX', '<cmd>OpenUrlInBuffer<cr>')
  vim.keymap.set('n', 'gF', '<cmd>OpenOrCreateFile<cr>')
  vim.keymap.set('n', 'gcb', '<cmd>BoxComment<cr>')
  vim.keymap.set('i', '<C-l>', '<cmd>Leap<CR>')
  vim.keymap.set('n', '<leader>ts', '<cmd>Scratch<cr>')
  vim.keymap.set('n', '<leader>s', '<cmd>ToggleWorld<cr>')
  vim.keymap.set('n', '<leader>j', '<cmd>SmartDuplicate<cr>')
  vim.keymap.set('n', '<leader>`', '<cmd>ToggleTitleCase<cr>')

  -- Git: ========================================================================================
  vim.keymap.set('n', '<leader>gg', '<cmd>Lazygit<cr>')
  vim.keymap.set('n', '<leader>ga', '<cmd>Git add .<cr>')
  vim.keymap.set('n', '<leader>gc', '<cmd>Git commit<cr>')
  vim.keymap.set('n', '<leader>gC', '<Cmd>Git commit --amend<cr>')
  vim.keymap.set('n', '<leader>gp', '<cmd>Git push -u origin main<cr>')
  vim.keymap.set('n', '<leader>gP', '<cmd>Git pull<cr>')
  vim.keymap.set('n', '<leader>gd', '<cmd>Git diff<cr>')
  vim.keymap.set('n', '<leader>gD', '<cmd>Git diff -- %<cr>')
  vim.keymap.set('n', '<leader>gs', '<cmd>lua MiniGit.show_at_cursor()<cr>')
  vim.keymap.set('n', '<leader>gS', [[<cmd>Git status -s<cr>]])
  vim.keymap.set('n', '<leader>gl', [[<cmd>Git log --pretty=format:\%h\ \%as\ │\ \%s --topo-order<cr>]])
  vim.keymap.set('n', '<leader>gx', [[<cmd>lua MiniGit.show_at_cursor()<cr>]])
  vim.keymap.set('n', '<leader>gh', [[<cmd>lua MiniDiff.toggle_overlay()<cr>]])
  vim.keymap.set('n', '<leader>go', [[<cmd>lua MiniDiff.toggle_overlay()<cr>]])
  vim.keymap.set('n', '<leader>gq', [[<cmd>MiniDiffInQuickFixList<cr>]])

  -- Picker ======================================================================================
  vim.keymap.set('n', '<leader>sf', '<cmd>PickFiles<cr>')
  vim.keymap.set('n', '<leader>fd', '<cmd>PickZoxide<cr>')
  vim.keymap.set('n', '<leader>ff', '<cmd>Pick files<cr>')
  vim.keymap.set('n', '<leader>fr', '<cmd>Pick oldfiles<cr>')
  vim.keymap.set('n', '<leader>ft', '<cmd>Pick grep_live<cr>')
  vim.keymap.set('n', '<leader>fb', '<cmd>Pick buffers<cr>')
  vim.keymap.set('n', '<leader>fe', '<cmd>Pick explorer<cr>')
  vim.keymap.set('n', '<leader>fo', '<cmd>Pick options<cr>')
  vim.keymap.set('n', '<leader>fp', '<cmd>Pick projects<cr>')
  vim.keymap.set('n', '<leader>fa', '<cmd>Pick home<cr>')
  vim.keymap.set('n', '<leader>fk', '<cmd>Pick keymaps<cr>')
  vim.keymap.set('n', '<leader>fc', '<cmd>Pick commands<cr>')
  vim.keymap.set('n', '<leader>fh', '<cmd>Pick history<cr>')
  vim.keymap.set('n', '<leader>fy', '<cmd>Pick colorschemes<cr>')
  vim.keymap.set('n', '<leader>fl', '<cmd>Pick buf_lines scope="current"<cr>')
  vim.keymap.set('n', '<leader>fgf', '<cmd>Pick git_files<cr>')
  vim.keymap.set('n', '<leader>fgh', '<cmd>Pick git_hunks<cr>')
  vim.keymap.set('n', '<leader>fgc', '<cmd>Pick git_commits<cr>')
  vim.keymap.set('n', '<leader>fgb', '<cmd>Pick git_branches<cr>')

  -- Bracketed: ==================================================================================
  vim.keymap.set('n', '[a', '<cmd>previous<cr>')
  vim.keymap.set('n', ']a', '<cmd>next<cr>')
  vim.keymap.set('n', '[b', '<cmd>bprevious<cr>')
  vim.keymap.set('n', ']b', '<cmd>bnext<cr>')
  vim.keymap.set('n', '[B', '<cmd>bfirst<cr>')
  vim.keymap.set('n', ']B', '<cmd>blast<cr>')
  vim.keymap.set('n', '[q', '<cmd>cprevious<cr>')
  vim.keymap.set('n', ']q', '<cmd>cnext<cr>')
  vim.keymap.set('n', '[Q', '<cmd>cfirst<cr>')
  vim.keymap.set('n', ']Q', '<cmd>clast<cr>')
  vim.keymap.set('n', '[l', '<cmd>lprevious<cr>')
  vim.keymap.set('n', ']l', '<cmd>lnext<cr>')
  vim.keymap.set('n', '[t', '<cmd>tprevious<cr>')
  vim.keymap.set('n', ']t', '<cmd>tnext<cr>')
  vim.keymap.set('n', '[T', '<cmd>tfirst<cr>')
  vim.keymap.set('n', ']T', '<cmd>tlast<cr>')
  vim.keymap.set('n', '[f', '<cmd>RelativeFilePrev<cr>')
  vim.keymap.set('n', ']f', '<cmd>RelativeFileNext<cr>')
  vim.keymap.set('n', '[p', '<Cmd>exe "put! " . v:register<CR>')
  vim.keymap.set('n', ']P', '<Cmd>exe "put "  . v:register<CR>')
  vim.keymap.set('n', '[<space>', "<cmd><c-u>put! =repeat(nr2char(10), v:count1)<cr>'[")
  vim.keymap.set('n', ']<space>', "<cmd><c-u>put =repeat(nr2char(10), v:count1)<cr>']")
  vim.keymap.set('n', '[h', function() require('mini.diff').goto_hunk('prev') end)
  vim.keymap.set('n', ']h', function() require('mini.diff').goto_hunk('next') end)
  vim.keymap.set('n', '[d', function() vim.diagnostic.jump({ count = -1, float = true }) end)
  vim.keymap.set('n', ']d', function() vim.diagnostic.jump({ count = 1, float = true }) end)
  vim.keymap.set('n', ']l', function() vim.diagnostic.jump({ count = 1, wrap = false }) end)
  vim.keymap.set('n', '[l', function() vim.diagnostic.jump({ count = -1, wrap = false }) end)
  vim.keymap.set('n', ']e', function() vim.diagnostic.jump({ count = 1, severity = vim.diagnostic.severity.ERROR }) end)
  vim.keymap.set('n', '[e', function() vim.diagnostic.jump({ count = -1, severity = vim.diagnostic.severity.ERROR }) end)
end)
