#!/usr/bin/env bash
# =============================================================================== #
# PowerMenu:                                                                      #
# =============================================================================== #
SELECTION="$(printf "1 - Lock\n2 - Suspend\n3 - Log out\n4 - Soft reboot\n5 - Hard reboot\n6 - Shutdown" | fuzzel --dmenu -l 6 -p "Power Menu: ")"
case $SELECTION in
	*"Lock")
		swaylock;;
	*"Suspend")
		doas zzz;;
	*"Log out")
		niri msg action quit;;
	*"Soft reboot")
		doas reboot;;
	*"Hard reboot")
		pkexec "echo b > /proc/sysrq-trigger";;
	*"Shutdown")
		doas poweroff;;
esac
