#!/usr/bin/env bash
# =============================================================================== #
# Umount:                                                                         #
# =============================================================================== #
# Define Variables: ==============================================================================
directory="/run/media/${USER}/"
removable="$(ls "$directory")"
lines="$(ls "$directory" | wc -l)"

# Check if drives is mounted: ====================================================================
[ "$lines" = "0" ] && notify-send "No removable drives mounted." && exit 1

# Display menu: ==================================================================================
selection="$(echo "$removable" | fuzzel -p "Umount Menu: " --dmenu -l "$lines")"
[ -z "$selection" ] && exit 1

# Umount selected drive: =========================================================================
doas umount "${directory}/${selection}"
