#!/usr/bin/env bash
# =============================================================================== #
# Umount:                                                                         #
# =============================================================================== #
directory="/run/media/${USER}/"
removable="$(ls "$directory")"
lines="$(ls "$directory" | wc -l)"

[ "$lines" = "0" ] && notify-send "No removable drives mounted." && exit 1

selection="$(echo "$removable" | fuzzel -p "Umount Menu: " --dmenu -l "$lines")"

[ -z "$selection" ] && exit 1

doas umount "${directory}/${selection}"
