# =============================================================================== #
# Bluetui:                                                                        #
# =============================================================================== #
layout = "SpaceBetween"
width = "auto"
toggle_scanning = "s"
esc_quit = true

# =============================================================================== #
# Adapter:                                                                        #
# =============================================================================== #
[adapter]
toggle_pairing = "p"
toggle_power = "o"
toggle_discovery = "d"

# =============================================================================== #
# Paired:                                                                         #
# =============================================================================== #
[paired_device]
unpair = "u"
toggle_trust = "t"
toggle_favorite = "f"
rename = "e"
