# =============================================================================== #
# Exports:                                                                        #
# =============================================================================== #
export PROMPT_COMMAND='history -a'
export HISTFILESIZE=5000
export HISTCONTROL=ignoreboth:erasedups
export LC_ALL="C.UTF-8"
export LANG="C"
export CC="gcc"
export LIBVA_DRIVER_NAME='i965'
export TERMINAL="alacritty"
export BROWSER="firefox"
export PAGER="less"
export EDITOR="nvim"
export VISUAL="nvim"
export GTK_THEME=Kripton
export XCURSOR_THEME=BreezeX-Black
export XCURSOR_SIZE=30

# =============================================================================== #
# Clean ~:                                                                        #
# =============================================================================== #
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export MYVIMRC="$HOME/.config/nvim/init.lua"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_CACHE_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export IPYTHONDIR="$HOME/.cache/ipython_config"
export JUPYTER_CONFIG_DIR="$HOME/.cache/jupyter_config"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rc"
export XDEB_PKGROOT=${HOME}/.config/xdeb
export KOMOREBI_CONFIG_HOME="$HOME/.config/komorebi"
export BUN_INSTALL_CACHE_DIR="$HOME/.cache/bun/install/cache"
export NI_CONFIG_FILE="$HOME/.config/ni/nirc"
export NI_DEFAULT_AGENT="npm"
export NI_GLOBAL_AGENT="npm"
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'

# =============================================================================== #
# Shell Options:                                                                  #
# =============================================================================== #
set -o vi
shopt -s cdable_vars
shopt -s autocd
shopt -s cdspell
shopt -s dirspell
shopt -s dotglob
shopt -s extglob
shopt -s no_empty_cmd_completion
shopt -s nocaseglob
shopt -s histappend

# =============================================================================== #
# Prompt:                                                                         #
# =============================================================================== #
export PS1='\[\033[38;2;166;227;161m\]\u\[\033[0m\]@\[\033[38;2;137;180;250m\]\h\[\033[0m\]:\[\033[38;2;249;226;175m\]\w\[\033[0m\]\[\033[38;2;205;214;244m\]\$ \[\033[0m\]'

# =============================================================================== #
# Autocomplete:                                                                   #
# =============================================================================== #
source <(carapace _carapace)

# =============================================================================== #
# Zoxide:                                                                         #
# =============================================================================== #
eval "$(zoxide init bash)"

# =============================================================================== #
# Aliases:                                                                        #
# =============================================================================== #
# Changing "Ls" To "Eza":                                                         #
# =============================================================================== #
alias ls="eza --long --group --icons=auto --git --sort=name --group-directories-first"
alias ll="eza --long --group --icons=auto --git --sort=name --group-directories-first"
alias lt="eza --long --group --icons=auto --git --only-dirs --tree --level=3 --sort=modified"
# Cd To Zoxide:                                                                   #
# =============================================================================== #
alias cd="z"
alias cdf="zi"
# Fetch (System Info):                                                            #
# =============================================================================== #
alias fetch="fastfetch"
alias neofetch="fastfetch"
## NeoVim To Vim:                                                                 #
# =============================================================================== #
alias v="nvim"
alias vi="nvim"
alias nv="nvim"
alias vn="nvim"
alias vim="nvim"
alias vid="nohup neovide 2>/dev/null 1>&2 &"
alias nvd="nohup neovide 2>/dev/null 1>&2 &"
# Git Command:                                                                    #
# =============================================================================== #
alias g="git"
alias gi="git init"
alias gs="g status -s"
alias ga="g add --all"
alias gcl="g clone --depth=1"
alias gc="g commit -m"
alias gd="g diff"
alias gl="g log --oneline --graph --all -10"
alias gp="g push -uf origin main"
alias lg="lazygit"
# Scoop Pkg Manager:                                                              #
# =============================================================================== #
alias pu="doas xbps-install -Syu xbps && doas xbps-install -Su"
alias pi="doas xbps-install -S"
alias pr="doas xbps-remove -R"
alias pq="xbps-query -Rs"
alias pl="xbps-query -l"
alias pc="doas xbps-remove -Oo"
alias pclean="doas rm -rf /var/cache/xbps/*"
# For Configs Files:                                                              #
# =============================================================================== #
alias dots="cd ~/.local/way.dots/"
alias swayc="nvim ~/.config/sway/config"
alias wmc="nvim ~/.config/sway/config"
alias elvc="nvim ~/.config/elvish/ec.elv"
alias bashc="nvim ~/.bashrc"
# Others Usfeual Alias:                                                           #
# =============================================================================== #
alias yt-concats='yt-dlp --ignore-config --config-locations ~/config/yt-dlp/music'
alias yt-music='yt-dlp --ignore-config --config-locations ~/.config/yt-dlp/music'
alias man="tldr"
alias cat="bat"
alias cls="clear"

# =============================================================================== #
# Source Fzf Keybindingd:                                                         #
# =============================================================================== #
eval "$(fzf --bash)"
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_ALT_C_COMMAND="fd --type=d --no-hidden --strip-cwd-prefix --exclude .git"
export FZF_DEFAULT_OPTS="
    --prompt='󱓇  ' --layout=reverse
    --preview-window=right,30%
    --style=minimal --height=100% --border --preview-window right,40%
    --color fg:#DBD2C7,bg:#172526
    --color bg+:#233935,fg+:#DBD2C7
    --color hl:#88B497,hl+:#88B497,gutter:#172526
    --color pointer:#233935,info:#233935
    --color prompt:#88B497,
    --color border:#233935
    --bind 'tab:accept'
"

# =============================================================================== #
# Tab Completions:                                                                #
# =============================================================================== #
bind 'TAB:menu-complete'
bind '"\e[Z": menu-complete-backward'
bind 'set show-all-if-ambiguous off'
bind 'set menu-complete-display-prefix on'
bind 'set match-hidden-files off'
bind 'set completion-ignore-case on'

# =============================================================================== #
# System Path:                                                                    #
# =============================================================================== #
NPM_PACKAGES="${HOME}/.local/share/npm-packages"
export PATH="$HOME/.config/bin:$HOME/.cargo/bin:$HOME/.local/bin:$NPM_PACKAGES/bin:$PATH"
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"
