# =============================================================================== # */
# LockConf:                                                                       # */
# =============================================================================== # */
[main]
gtk-theme=Macro
time-format= %A, %b %d  %I:%M %p
