# =============================================================================== #
# Main:                                                                           #
# =============================================================================== #
[main]
gtk-theme=Macro
time-format=󰥔 %I:%M %p
