# =============================================================================== #
# Theme:                                                                          #
# =============================================================================== #
theme = "thorn"

# =============================================================================== #
# Editor:                                                                         #
# =============================================================================== #
# General: =======================================================================================
[editor]
true-color = true
auto-format = true
cursorline = true
auto-info = false
scrolloff = 99
completion-trigger-len = 1
default-yank-register = "+"
line-number = "absolute"
shell = ["bash", "-c"]
gutters = ["diagnostics", "diff", "line-numbers", "spacer"]

# Lsp: ===========================================================================================
[editor.lsp]
display-messages = true
auto-signature-help = false

# Cursor: ========================================================================================
[editor.cursor-shape]
normal = "block"
insert = "block"
select = "block"

# =============================================================================== #
# Keymaps:                                                                        #
# =============================================================================== #
# Normal: ========================================================================================
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
H = "goto_first_nonwhitespace"
L = "goto_line_end"
G = "goto_last_line"
V = ["select_mode", "extend_to_line_bounds"]
D = "kill_to_line_end"
X = ["select_mode", "select_line_above"]
x = ["select_mode", "select_line_below"]
"%" = ["select_mode", "select_all"]
"ret" = "goto_word"
"C-n" = "search_selection"

[keys.normal.space.f]
f = "file_picker"
b = "buffer_picker"
s = "symbol_picker"

# Select: ========================================================================================
[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
H = "goto_line_start"
L = "goto_line_end"
G = "goto_last_line"
V = "extend_to_line_bounds"
P = "replace_with_yanked"
X = "select_line_above"
x = "select_line_below"
"C-n" = "search_selection"
