# =============================================================================== #
# Theme:                                                                          #
# =============================================================================== #
theme                      = "thorn"

# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
[editor]
true-color                 = true
undercurl                  = true
auto-completion            = true
auto-info                  = true
cursorline                 = true
color-modes                = true
idle-timeout               = 40
text-width                 = 80
rulers                     = [100]
line-number                = "relative"
end-of-line-diagnostics    = "hint"
bufferline                 = "multiple"
scrolloff                  = 99
mouse                      = true
default-yank-register      = "+"
middle-click-paste         = true
scroll-lines               = 3
shell                      = ["elvish", "-c"]
cursorcolumn               = false
continue-comments          = false
gutters                    = ["diff", "diagnostics", "line-numbers", "spacer"]
path-completion            = true
completion-timeout         = 150
preview-completion-insert  = false
completion-trigger-len     = 1
completion-replace         = true
default-line-ending        = "lf"
insert-final-newline       = false
atomic-save                = true
trim-final-newlines        = true
trim-trailing-whitespace   = true
popup-border               = "all"
indent-heuristic           = "simple"
jump-label-alphabet        = "jklmasdfghwobceinpqrtuvxyz"
clipboard-provider         = "wayland"
editor-config              = true
auto-format                = true

# =============================================================================== #
# Statusline:                                                                     #
# =============================================================================== #
[editor.statusline]
left = [ "mode", "version-control", "read-only-indicator", "file-name", "file-modification-indicator", ]
center = ["diagnostics"]
right = [ "register", "position", "primary-selection-length", "selections", "file-encoding", "file-indent-style", "file-line-ending", "position-percentage", "file-type", "spacer" ]
mode.normal = " "
mode.insert = " "
mode.select = " "
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

# =============================================================================== #
# Cursor:                                                                         #
# =============================================================================== #
[editor.cursor-shape]
insert                     = "bar"
normal                     = "block"
select                     = "underline"

# =============================================================================== #
# Indent:                                                                         #
# =============================================================================== #
[editor.indent-guides]
render = true
character = "╎"
skip-levels = 0

# =============================================================================== #
# Autopairs:                                                                      #
# =============================================================================== #
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

# =============================================================================== #
# Picker:                                                                         #
# =============================================================================== #
[editor.file-picker]
hidden          = true
git-ignore      = true
follow-symlinks = true

# =============================================================================== #
# Autosave:                                                                       #
# =============================================================================== #
[editor.auto-save]
focus-lost          = true
after-delay.enable  = true
after-delay.timeout = 30000

# =============================================================================== #
# Lsp:                                                                            #
# =============================================================================== #
[editor.lsp]
enable                    = true
display-messages          = true
display-progress-messages = true

# =============================================================================== #
# Diagnostics:                                                                    #
# =============================================================================== #
[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

# =============================================================================== #
# keymaps:                                                                        #
# =============================================================================== #
# Insert: ========================================================================================
[keys.insert]
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"

# Select: ========================================================================================
[keys.select]
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"

# Normal: ========================================================================================
[keys.normal]
up    = "no_op"
down  = "no_op"
left  = "no_op"
right = "no_op"

tab = ":buffer-next"
S-tab = ":buffer-previous"

"C-h" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
"C-l" = "jump_view_left"

[keys.normal.t]
"T" = "file_explorer"

[keys.normal." "]
"l" = { "g" = [ ":write-all", ":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all" ]}
"w" = ":write"
"q" = ":quit"

[keys.normal.h]
"K" = ":hsplit"
"L" = ":vsplit"
