# =============================================================================== #
# Theme:                                                                          #
# =============================================================================== #
[mgr]
marker_copied = { fg = "#87a987", bg = "#76946a" }
marker_cut = { fg = "#c4746e", bg = "#e46876" }
marker_marked = { fg = "#8992a7", bg = "#54546d" }
marker_selected = { fg = "#dca561", bg = "#ffa066" }
cwd = { fg = "#e6c384" }
find_keyword = { fg = "#dca561", bg = "#201d1d" }
find_position = {}
count_copied = { fg = "#201d1d", bg = "#87a987" }
count_cut = { fg = "#201d1d", bg = "#c4746e" }
count_selected = { fg = "#201d1d", bg = "#dca561" }
border_symbol = "│"
border_style = { fg = "#252535" }

[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = false }
padding = { open = "█", close = "█" }

[tabs]
active = { fg = "#201d1d", bg = "#8ba4b0" }
inactive = { fg = "#8ba4b0", bg = "#2a2a37" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }


[mode]
normal_main = { fg = "#201d1d", bg = "#8ba4b0" }
normal_alt = { fg = "#8ba4b0", bg = "#2a2a37" }
select_main = { fg = "#201d1d", bg = "#8992a7" }
select_alt = { fg = "#8992a7", bg = "#2a2a37" }
unset_main = { fg = "#201d1d", bg = "#e6c384" }
unset_alt = { fg = "#e6c384", bg = "#2a2a37" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { fg = "#c8c093", bg = "#16161d" }
progress_label = { fg = "#8ba4b0", bold = true }
progress_normal = { fg = "#2a2a37", bg = "#201d1d" }
progress_error = { fg = "#2a2a37", bg = "#201d1d" }
perm_type = { fg = "#87a987" }
perm_read = { fg = "#e6c384" }
perm_write = { fg = "#ff5d62" }
perm_exec = { fg = "#7aa89f" }
perm_sep = { fg = "#8992a7" }

[select]
border   = { fg = "#c4746e" }
active   = { fg = "#a292a3", bold = true }
inactive = {}

[pick]
border = { fg = "#658594" }
active = { fg = "#8992a7", bold = true }
inactive = {}

[input]
border = { fg = "#658594" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#658594" }
active = { reversed = true }
inactive = {}
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border = { fg = "#658594" }
title = {}
hovered = { fg = "#8992a7" }

[which]
cols = 3
mask = { bg = "#16161d" }
rest = { fg = "#727169" }
cand = { fg = "#8ba4b0" }
desc = { fg = "#54546d" }
separator = "  "
separator_style = { fg = "#a6a69c" }

[help]
on = { fg = "#7aa89f" }
run = { fg = "#8992a7" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#201d1d", bg = "#dcd7ba"}

[notify]
title_info = { fg = "#87a987" }
title_warn = { fg = "#e6c384" }
title_error = { fg = "#ff5d62" }
icon_info  = ""
icon_warn  = ""
icon_error = ""

[filetype]
rules = [
    # images
    { mime = "image/*", fg = "#e6c384" },

    # media
    { mime = "{audio,video}/*", fg = "#8992a7" },

    # archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#c4746e" },

    # documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#6a9589" },

    # broken links
    { url = "*", is = "orphan", fg = "#c34043" },

    # executables
    { url = "*", is = "exec", fg = "#76946a" },

    # fallback
    { url = "*", fg = "#8ba4b0" },
    { url = "*/", fg = "#8ba4b0" },
]
