# =============================================================================== #
# Yazi:                                                                           #
# =============================================================================== #
[mgr]
show_hidden = false
show_symlink = false
ratio = [0, 4, 8]
sort_by = "natural"
sort_dir_first = true
sort_translit = true
sort_sensitive = false
sort_reverse = false
scrolloff = 0
linemode = "mtime"
title_format = "{cwd}"
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[preview]
wrap = "no"
tab_size = 2
max_width = 1200
max_height = 1800
image_quality = 90

[input]
cursor_blink = true

[opener]
edit = [
	{ run = '$EDITOR %s', block = true, for = "unix" },
	{ run = "nvim %*",   block = true, for = "windows" },
	{ run = "nvim %*",   orphan = true, for = "windows" },
]
play = [
	{ run = "mpv %s", orphan = true, for = "unix" },
	{ run = 'mpv.exe %*', orphan = true, for = "windows" },
]
show = [
	{ run = 'imv %s', orphan = true, for = "unix" },
	{ run = 'qview.exe %*', orphan = true, for = "windows" },
]
showPDF = [
	{ run = 'zathura %s', orphan = true, for = "unix" },
	{ run = 'sumatrapdf.exe %*', orphan = true, for = "windows" },
]
extract = [
	{ run = 'ouch d -y %s', desc = "Extract here with ouch", for = "unix" },
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
]
archive = [
	{ run = 'unar "$1"', desc = "Extract here" },
	{ run = 'unar "%1"', desc = "Extract here", for = "windows" },
	{ run = '/Applications/MacZip.app/Contents/MacOS/MacZip "$1"', orphan = true, desc = "MacZip" },
]
reveal = [
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
	{ run = 'open -R "$1"',                          desc = "Reveal", for = "macos" },
	{ run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
]
open = [
	{ run = "xdg-open %s1", desc = "Open" },
	{ run = 'start msedge "%*"', desc = "Open" },
	{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },

]

[open]
rules = [
	{ url = "*.html", use = [ "open", "edit" ] },
	{ mime = "text/*",  use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "show", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },
  { mime = "application/pdf", use = [ "showPDF", "reveal" ] },
	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },
	{ mime = "application/zip",             use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/gzip",            use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-tar",           use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-bzip",          use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-bzip2",         use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-rar",           use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/xz",              use = [ "extract", "reveal" ] },
]

[plugin]
prepend_previewers = [
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
]
