# =============================================================================== #
# Fuzzel:                                                                         #
# =============================================================================== #
[main]
font=JetBrainsMono Nerd Font:size=11
use-bold=yes
dpi-aware=no
fields=name,generic,comment,categories,filename,keywords,exec
terminal=foot
prompt=""
placeholder="Search and Choose"
icon-theme=Papirus-Dark
icons-enabled=yes
show-actions=no
anchor=center
x-margin=10
y-margin=10
lines=18
width=55
horizontal-pad=10
vertical-pad=15
inner-pad=15
line-height=25
letter-spacing=0
image-size-ratio=0.2
layer=overlay
exit-on-keyboard-focus-loss = yes

[colors]
background=0d0c0cff
prompt=b4b3a7ff
input=b4b3a7ff
text=938aa9ff
match=8ba4b0ff
selection=201d1dff
selection-text=c5c9c5ff
border=252535ff

[border]
width=2
radius=0

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+g Control+c Control+bracketleft
execute=Return KP_Enter Control+y Tab
execute-or-next=Control+n
execute-input=Shift+Return Shift+KP_Enter
cursor-left=Left Control+b
cursor-left-word=Control+Left Mod1+b
cursor-right=Right Control+f
cursor-right-word=Control+Right Mod1+f
cursor-home=Home Control+a
cursor-end=End Control+e
delete-line=Control+Shift+BackSpace
delete-prev=BackSpace Control+h
delete-prev-word=Mod1+BackSpace Control+BackSpace Control+w
delete-line-backward=Control+u
delete-next=Delete KP_Delete Control+d
delete-next-word=Mod1+d Control+Delete Control+KP_Delete
delete-line-forward=Control+q
prev=Up Control+p Control+k
prev-with-wrap=ISO_Left_Tab
prev-page=Page_Up KP_Page_Up
next=Down Control+j
next-with-wrap=none
next-page=Page_Down KP_Page_Down
expunge=Shift+Delete
clipboard-paste=Control+v XF86Paste
primary-paste=Shift+Insert Shift+KP_Insert
