# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
[main]
font=JetBrainsMono Nerd Font:size=12
use-bold=yes
dpi-aware=no
fields=name,generic,comment,categories,filename,keywords,exec
terminal=foot
prompt=""
placeholder="Search and Choose"
icon-theme=Kora
icons-enabled=yes
show-actions=no
anchor=center
x-margin=10
y-margin=10
lines=18
width=60
horizontal-pad=10
vertical-pad=15
inner-pad=15
line-height=25
letter-spacing=0
image-size-ratio=0.2
layer=overlay
exit-on-keyboard-focus-loss = yes

# =============================================================================== #
# Colorscheme:                                                                    #
# =============================================================================== #
[colors]
background=172526ff
text=DBD2C7ff
message=DBD2C7ff
prompt=88B497ff
placeholder=568270ff
input=DBD2C7ff
match=88B497ff
selection=233935ff
selection-text=DBD2C7ff
selection-match=88B497ff
counter=568270ff
border=233935ff

# =============================================================================== #
# Border:                                                                         #
# =============================================================================== #
[border]
width=1
radius=0

# =============================================================================== #
# Dmenu:                                                                          #
# =============================================================================== #
[dmenu]
exit-immediately-if-empty=yes

# =============================================================================== #
# keybidings:                                                                     #
# =============================================================================== #
[key-bindings]
cancel=Escape Control+g Control+c Control+bracketleft
execute=Return KP_Enter Control+y Tab
execute-or-next=Control+n
execute-input=Shift+Return Shift+KP_Enter
cursor-left=Left Control+b
cursor-left-word=Control+Left Mod1+b
cursor-right=Right Control+f
cursor-right-word=Control+Right Mod1+f
cursor-home=Home Control+a
cursor-end=End Control+e
delete-line=Control+Shift+BackSpace
delete-prev=BackSpace Control+h
delete-prev-word=Mod1+BackSpace Control+BackSpace Control+w
delete-line-backward=Control+u
delete-next=Delete KP_Delete Control+d
delete-next-word=Mod1+d Control+Delete Control+KP_Delete
delete-line-forward=Control+q
prev=Up Control+p Control+k
prev-with-wrap=ISO_Left_Tab
prev-page=Page_Up KP_Page_Up
next=Down Control+j
next-with-wrap=none
next-page=Page_Down KP_Page_Down
expunge=Shift+Delete
clipboard-paste=Control+v XF86Paste
primary-paste=Shift+Insert Shift+KP_Insert
