# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
[main]
font=JetBrainsMono Nerd Font:size=12:weight=semibold
font-bold=JetBrainsMono Nerd Font:size=12:weight=extrabold
font-italic=JetBrainsMono Nerd Font:size=12:weight=semibold:slant:italic
font-bold-italic=JetBrainsMono Nerd Font:size=12:weight=extrabold:slant:italic
shell=elvish
pad=0x0 center
letter-spacing=0px
horizontal-letter-offset=0
vertical-letter-offset=0
line-height = 16.5
box-drawings-uses-font-glyphs=no
initial-window-size-pixels = 1300x800
resize-by-cells=no

# =============================================================================== #
# Cursor:                                                                         #
# =============================================================================== #
[cursor]
style=block
blink=no

# =============================================================================== #
# Bell:                                                                           #
# =============================================================================== #
[bell]
urgent=yes

# =============================================================================== #
# Colorscheme:                                                                    #
# =============================================================================== #
[colors-dark]
# Primary: =======================================================================================
background= 172526
foreground= d8d8d8

# Cursor: ========================================================================================
cursor = 172526 DBD2C7

# Selection: ========================================================================================
selection-foreground = DBD2C7
selection-background = 233935

# Normal: ========================================================================================
regular0=    172526
regular1=   D2696C
regular2=    88B497
regular3=   FFD7AA
regular4=   91C4C0
regular5=   F9ADA0
regular6=   87CBB1
regular7=   A1A790

# Bright: ========================================================================================
bright0=     568270
bright1=    D2696C
bright2=    88B497
bright3=    FFD7AA
bright4=    91C4C0
bright5=    F9ADA0
bright6=    87CBB1
bright7=    DBD2C7

# =============================================================================== #
# scrolling:                                                                      #
# =============================================================================== #
[scrollback]
lines=20000
indicator-position=none

# =============================================================================== #
# keybidings:                                                                     #
# =============================================================================== #
# General: =======================================================================================
[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=none

# Search: ========================================================================================
[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G
delete-prev-word=Control+BackSpace

# Text: ==========================================================================================
[text-bindings]
\x03=Control+c
