# =============================================================================== #
# Fnott:                                                                          #
# =============================================================================== #
# General: =======================================================================================
anchor=bottom-left
border-radius=1
border-size=0
notification-margin=10
min-width=400
layer=overlay
icon-theme=Papirus-Dark
max-icon-size=64
padding-vertical=20
padding-horizontal=20
progress-bar-height=12
max-timeout=10
selection-helper=fuzzel --dmenu
summary-format=<b>%s</b>
# Font: ==========================================================================================
title-font=JetBrainsMono Nerd Font:pixelsize=10
summary-font=JetBrainsMono Nerd Font:pixelsize=14
body-font=JetBrainsMono Nerd Font:pixelsize=12
# Color: =========================================================================================
title-color=a6adc8ff
summary-color=cdd6f4ff
body-color=cdd6f4ff
background=1e1e2eff
border-color=89b4faff
progress-color=6c7086ff

# =============================================================================== #
# Profile:                                                                        #
# =============================================================================== #
# Low: ===========================================================================================
[low]
background=a2bab1ff
title-color=282828e0
summary-color=282828e0
body-color=282828e0
progress-color=282828e0
icon=dialog-information
# Normal: ========================================================================================
[normal]
background=131313ff
icon=dialog-information
# Critical: ========================================================================================
[critical]
background=802523ff
title-color=ebdbb2ff
summary-color=ebdbb2ff
body-color=ebdbb2ff
icon=dialog-warning
