# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
title-font=JetBrainsMono Nerd Font:pixelsize=12
summary-font=JetBrainsMono Nerd Font:pixelsize=12
body-font=JetBrainsMono Nerd Font:pixelsize=12
anchor=bottom-left
border-radius=1
border-size=1
notification-margin=5
min-width=300
layer=overlay
icon-theme=Papirus-Dark
max-icon-size=64
padding-vertical=15
padding-horizontal=15
progress-bar-height=15
max-timeout=10
selection-helper=fuzzel --dmenu
summary-format=<b>%s</b>
title-format=<b>%a%A</b>
title-color=88B497ff
summary-color=DBD2C7ff
body-color=DBD2C7ff
background=172526ff
border-color=233935ff
progress-color=87CBB1ff

# =============================================================================== #
# Profiles:                                                                       #
# =============================================================================== #
# Low: ===========================================================================================
[low]
background=a2bab1ff
title-color=568270e0
summary-color=568270e0
body-color=568270e0
progress-color=568270e0
icon=dialog-information

# Normal: ========================================================================================
[normal]
background=172526ff
icon=dialog-information

# Critical: ======================================================================================
[critical]
background=D2696Cff
title-color=DBD2C7ff
summary-color=DBD2C7ff
body-color=DBD2C7ff
icon=dialog-warning
