# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
"type" = "green_2"
"type.enum.variant" = "green_2"
"constant" = "yellow"
"constant.numeric" = "yellow"
"constant.character" = "yellow"
"constant.character.escape" = "yellow"
"string" = "green_3"
"string.regexp" = "blue"
"string.special" = "blue"
"string.special.symbol" = "red"
"comment" = "green_5"
"variable" = "fg"
"variable.parameter" = "fg"
"variable.builtin" = "yellow"
"variable.other.member" = "green_0"
"label" = "blue"
"punctuation" = "green_0"
"punctuation.special" = "green_0"
"punctuation.delimiter" = "green_0"
"punctuation.bracket" = "gray"
"keyword" = "orange"
"keyword.directive" = "orange"
"keyword.control.conditional" = { fg = "mauve", modifiers = ["italic"] }
"operator" = "red"
"function" = "blue"
"function.builtin" = "blue"
"function.macro" = "blue"
"tag" = "blue"
"namespace" = "green_0"
"attribute" = "green_0"
"constructor" = "green_2"
"module" = "green_2"
"special" = "green_0"

# =============================================================================== #
# Markup:                                                                         #
# =============================================================================== #
"markup.heading.marker" = "grey2"
"markup.heading.1" = { fg = "green_2", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green_3", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.list" = "blue"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "orange"
"markup.quote" = "gray"
"markup.raw" = "green_3"

# =============================================================================== #
# Diff:                                                                           #
# =============================================================================== #
"diff.plus" = "git_add"
"diff.delta" = "git_change"
"diff.minus" = "git_delete"

# =============================================================================== #
# Diagnostic:                                                                     #
# =============================================================================== #
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "green_0", style = "curl" }}
"warning" = "yellow"
"error" = "red"
"info" = "blue"
"hint" = "gray"

# =============================================================================== #
# Editor:                                                                         #
# =============================================================================== #
"ui.background" = { fg = "bg_visual", bg = "bg" }
"ui.background.separator" = "bg_visual"
"ui.cursor" = { fg = "bg", bg = "fg" }
"ui.cursor.match" = { fg = "orange", bg = "bg_yellow" }
"ui.cursor.insert" = { fg = "bg", bg = "gray" }
"ui.cursor.select" = { fg = "bg", bg = "blue" }
"ui.cursorline.primary" = { bg = "cursorline" }
"ui.cursorline.secondary" = { bg = "cursorline" }
"ui.selection" = { bg = "bg_visual" }
"ui.linenr" = "number"
"ui.linenr.selected" = 'yellow'
"ui.statusline" = { fg = "statusline_fg", bg = "statusbar_bg" }
"ui.statusline.inactive" = { fg = "fg", bg = "statusbar_bg" }
"ui.statusline.normal" = { fg = "statusbar_bg", bg = "grey", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "statusbar_bg", bg = "yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "statusbar_bg", bg = "blue", modifiers = ["bold"] }
"ui.bufferline" = { fg = "green_5", bg = "bg_float" }
"ui.bufferline.active" = { fg = "green_0", bg = "bg_float", modifiers = ["bold"] }
"ui.popup" = { fg = "green_3", bg = "bg_float" }
"ui.window" = { fg = "green_3", bg = "bg_float" }
"ui.help" = { fg = "green_3", bg = "bg_float" }
"ui.text" = "fg"
"ui.text.focus" = "fg"
"ui.menu" = { fg = "fg", bg = "bg_float" }
"ui.menu.selected" = { fg = "fg", bg = "bg_visual" }
"ui.virtual.whitespace" = { fg = "sep" }
"ui.virtual.indent-guide" = { fg = "sep" }
"ui.virtual.ruler" = { bg = "bg_float" }
"ui.virtual.inlay-hint" = "grey"

# =============================================================================== #
# Palette:                                                                        #
# =============================================================================== #
[palette]
# Primary: =======================================================================================
bg             = "#172526"
fg             = "#DBD2C7"
bg_float       = "#131F20"
bg_visual      = "#26403E"

# General: =======================================================================================
number         = "#1C3D3C"
cursorline     = "#1D3334"
separator      = "#0B1213"

# Colors: ========================================================================================
white         = "#DBD2C7"
gray          = "#9B9A8C"
green_0       = "#B8CDB6"
green_1       = "#9EBB9C"
green_2       = "#88B497"
green_3       = "#9EC59B"
green_4       = "#6FA791"
green_5       = "#568270"
green_6       = "#87CBB1"
yellow        = "#FFD7AA"
orange        = "#F2A597"
blue          = "#91C4C0"
red           = "#D2696C"
magenta       = "#F9ADA0"

# Statusbar: =====================================================================================
statusbar_fg  = "#9EC59B"
statusbar_bg  = "#131F20"
statusbar_sep = "#233935"

# Diff: ==========================================================================================
diff_add      = "#1F3329"
diff_change   = "#1E2D39"
diff_delete   = "#33232A"

# Git: ===========================================================================================
git_add       = "#94C68B"
git_change    = "#6DAAE3"
git_delete    = "#D8464B"
